[tool.poetry]
name = "cadbuildr-stdlib"
version = "0.0.0.1"
description = "Standard library for cadbuildr with tools, parts, assemblies built on top of foundation"
authors = ["Cadbuildr Team"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.cadbuildr.dependencies]
foundation "^0.0.0.12"
